HelpOn/Controllers/FuncionarioController.cs
using HelpOn.Dominio.Models;
using HelpOn.Persistencia.UnitOfWork;
using HelpOn.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HelpOn.Controllers
{
    public class FuncionarioController : Controller
    {

        #region FIELD

        private UnitOfWork _unit = new UnitOfWork();

        #endregion

        #region GET

        [HttpGet]
        public ActionResult ListarFuncionarios()
        {
            var msg = TempData["mensagem"];
            var viewmodel = new FuncionarioViewModel()
            {
                Funcionarios = _unit.FuncionarioRepository.Listar()
            };


            return View(viewmodel);
        }

        [HttpGet]
        public ActionResult Cadastrar(string msg)
        {
            var viewModel = new FuncionarioViewModel()
            {
                Mensagem = msg,
                ListaNivel = ListarNivel()
            };
            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var funcionario = _unit.FuncionarioRepository.BuscarPorId(id);
            var viewmodel = new FuncionarioViewModel()
            {
                Nome = funcionario.Nome,
                CPF = funcionario.CPF,
                Email = funcionario.Email,
                Senha = funcionario.Senha,
                DataCadastro = funcionario.DataCadastro,
                Nivel = funcionario.Nivel
            };
            return View(viewmodel);

        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            ICollection<Nivel> nivel = _unit.NivelRepository.Listar();
            ViewBag.Niveis = nivel;
            var funcionario = _unit.FuncionarioRepository.BuscarPorId(id);
            var viewmodel = new FuncionarioViewModel()
            {
                IDFuncionario = funcionario.IDFuncionario,
                Nome = funcionario.Nome,
                CPF = funcionario.CPF,
                Email = funcionario.Email,
                Senha = funcionario.Senha,
                DataCadastro = funcionario.DataCadastro,
                Nivel = funcionario.Nivel,
                IDNivel = funcionario.IDNivel
            };
            return View(viewmodel);

        }

        #endregion

        #region POST

        [HttpPost]
        public ActionResult Cadastrar(FuncionarioViewModel funcionarioViewModel, string repeatsenha)
        {

            if (funcionarioViewModel.Senha != repeatsenha) ModelState.AddModelError("repeatsenha", "As senhas não correspondem.");

            if (ModelState.IsValid)
            {
                var funcionario = new Funcionario()
                {
                    Nome = funcionarioViewModel.Nome,
                    CPF = funcionarioViewModel.CPF,
                    Email = funcionarioViewModel.Email,
                    Senha = funcionarioViewModel.Senha,
                    DataCadastro = DateTime.Now,
                    IDNivel = funcionarioViewModel.IDNivel
                };

                _unit.FuncionarioRepository.Cadastrar(funcionario);

                try
                {
                    _unit.Salvar();
                }
                catch (Exception e)
                {
                    funcionarioViewModel.Mensagem = "Ocorreu um erro ao tentar cadastrar o funcionário, por favor tente mais tarde." + "Erro: " + e;
                    funcionarioViewModel.ListaNivel = ListarNivel();
                    return View(funcionarioViewModel);
                }

                TempData["mensagem"] = "Funcionário cadastrado com sucesso!";
                return RedirectToAction("ListarFuncionarios");
            }
            else
            {
                funcionarioViewModel.ListaNivel = ListarNivel();
                return View(funcionarioViewModel);
            }

        }

        [HttpPost]
        public ActionResult Editar(Funcionario funcionario, string novasenha)
        {
            if(novasenha != "") funcionario.Senha = novasenha;
         

            _unit.FuncionarioRepository.Atualizar(funcionario);

            try
            {
                _unit.Salvar();
            }
            catch (Exception e)
            {
                TempData["mensagem"] = "Ocorreu um erro ao tentar editar o funcionário, por favor tente mais tarde." + "Erro: " + e;
                return RedirectToAction("ListarFuncionarios");
            }

            TempData["mensagem"] = "Funcionário editado com sucesso!";
            return RedirectToAction("ListarFuncionarios");


        }

        [HttpPost]
        public ActionResult Excluir(int IDFuncionario)
        {
            _unit.FuncionarioRepository.Remover(IDFuncionario);

            try
            {
                _unit.Salvar();
            }
            catch (Exception e)
            {
                TempData["mensagem"] = "Ocorreu um erro ao tentar excluir o funcionário, por favor tente mais tarde." + "Erro: " + e;
                return RedirectToAction("ListarFuncionarios");
            }

            TempData["mensagem"] = "Funcionário removido com sucesso!";
            return RedirectToAction("ListarFuncionarios");
        }

        #endregion

        #region PRIVATE
        private SelectList ListarNivel()
        {
            var lista = _unit.NivelRepository.Listar();
            return new SelectList(lista, "IDNivel", "Nome");
        }

        #endregion

        #region DISPOSE

        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }

        #endregion
    }
}

HelpOn/Controllers/LoginController.cs
using HelpOn.Dominio.Models;
using HelpOn.Persistencia.UnitOfWork;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HelpOn.Web.Controllers
{
    public class LoginController : Controller
    {
       
        private UnitOfWork _unit = new UnitOfWork();

        #region GET
        // GET: Login
        [HttpGet]
        public ActionResult Index(string msg)
        {
            ViewBag.Mensagem = msg;
            return View();
        }

      
        #endregion

        #region POST
        [HttpPost]
        public ActionResult Index(string Email, string Senha)
        {
            var Funcionario = _unit.FuncionarioRepository.BuscarLogin(a => a.Email.Contains(Email) && a.Senha == Senha);
            if (Funcionario != null)
            {
                //Adicionar Filtro de chamados pra gerente, suporte e monitor
                Session["usuarioLogado"] = Funcionario;
                return RedirectToAction("Index", "Chamado");
            }
           return RedirectToAction("Index", new { msg = "Login ou Senha incorretos" });
        }

        public ActionResult Sair()
        {
            Session["usuarioLogado"] = null;
            return RedirectToAction("Index");
        }
        #endregion
    }
}

HelpOn/Controllers/UnidadeController.cs
using HelpOn.Dominio.Models;
using HelpOn.Persistencia.UnitOfWork;
using HelpOn.ViewModel;
using HelpOn.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HelpOn.Controllers
{
    public class UnidadeController : Controller
    {

        private UnitOfWork _unit = new UnitOfWork();

        [HttpGet]
        public ActionResult ListarUnidades()
        {
            var msg = TempData["mensagem"];
            ICollection<Unidade> unidades = _unit.UnidadeRepository.Listar();

            return View(unidades);
        }


        [HttpGet]
        public ActionResult Cadastrar()
        {

            return View();
        }

        [HttpGet]
        public ActionResult Andares(string msg)
        {
            var viewmodel = new AndarViewModel()
            {
                Mensagem = msg,
                Andares = _unit.AndarRepository.Listar(),
                ListaUnidade = ListarUnidade()
            };
            return View(viewmodel);
        }

        private SelectList ListarAndar()
        {
            var lista = _unit.AndarRepository.Listar();
            return new SelectList(lista, "NumeroAndar", "NumeroAndar");
        }

        [HttpGet]
        public ActionResult Labs(string msg)
        {
            var viewmodel = new LaboratorioViewModel()
            {
                Mensagem = msg,
                Laboratorios = _unit.LaboratorioRepository.Listar(),
                ListaUnidade = ListarUnidade(),
                ListaAndar = ListarAndar()
            };
            return View(viewmodel);
        }

        [HttpPost]
        public ActionResult CadastroLabs(LaboratorioViewModel labViewModel)
        {
            if (ModelState.IsValid)
            {
                var laboratorio = new Laboratorio()
                {
                    NumeroAndar = labViewModel.NumeroAndar,
                    IDUnidade = labViewModel.IDUnidade,
                    NumeroLab = labViewModel.NumeroLab
                };

                _unit.LaboratorioRepository.Cadastrar(laboratorio);

                try
                {
                    _unit.Salvar();
                }
                catch (Exception e)
                {
                    labViewModel.Mensagem = "Ocorreu um erro ao tentar cadastrar o laboratório, por favor tente mais tarde." + "Erro: " + e;
                    labViewModel.ListaUnidade = ListarUnidade();
                    labViewModel.ListaAndar = ListarAndar();
                    return View("Labs", new { msg = "Laboratório cadastrado com sucesso!" });
                }

                return RedirectToAction("Labs", new { msg = "Laboratório cadastrado com sucesso!" });
            }
            else
            {
                labViewModel.ListaUnidade = ListarUnidade();
                labViewModel.ListaAndar = ListarAndar();
                return View("Labs");
            }
        }


        [HttpPost]
        public ActionResult CadastroAndares(AndarViewModel andarViewModel)
        {
            if (ModelState.IsValid)
            {
                var andar = new Andar()
                {
                    NumeroAndar = andarViewModel.NumeroAndar,
                    IDUnidade = andarViewModel.IDUnidade
                };

                _unit.AndarRepository.Cadastrar(andar);

                try
                {
                    _unit.Salvar();
                }
                catch (Exception e)
                {
                    andarViewModel.Mensagem = "Ocorreu um erro ao tentar cadastrar o andar, por favor tente mais tarde." + "Erro: " + e;
                    andarViewModel.ListaUnidade = ListarUnidade();
                    return View(andarViewModel);
                }

                return RedirectToAction("Andares", new { msg = "Andar cadastrado com sucesso!" });
            }
            else
            {
                andarViewModel.ListaUnidade = ListarUnidade();
                return View(andarViewModel);
            }
        }

        [HttpPost]
        public ActionResult ExcluirAndar(int NumeroAndar)
        {
            _unit.AndarRepository.Remover(NumeroAndar);

            try
            {
                _unit.Salvar();
            }
            catch (Exception e)
            {
                return RedirectToAction("Andares", new { msg = "Ocorreu um erro ao tentar excluir o andar, por favor tente mais tarde." + "Erro: " + e });
            }

            return RedirectToAction("Andares", new { msg = "Andar removido com sucesso!" });
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var unidade = _unit.UnidadeRepository.BuscarPorId(id);
            var viewmodel = new UnidadeViewModel()
            {
                Nome = unidade.Nome,
                IDUnidade = unidade.IDUnidade,
                CEP = unidade.CEP,
                Logradouro = unidade.Logradouro,
                Numero = unidade.Numero,
                Complemento = unidade.Complemento,
                Bairro = unidade.Bairro,
                Cidade = unidade.Cidade,
                DataCadastro = unidade.DataCadastro
            };
            return View(viewmodel);

        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var unidade = _unit.UnidadeRepository.BuscarPorId(id);
            var viewmodel = new UnidadeViewModel()
            {
                IDUnidade = unidade.IDUnidade,
                Nome = unidade.Nome,
                CEP = unidade.CEP,
                Logradouro = unidade.Logradouro,
                Numero = unidade.Numero,
                Complemento = unidade.Complemento,
                Bairro = unidade.Bairro,
                Cidade = unidade.Cidade,
                DataCadastro = unidade.DataCadastro

            };
            return View(viewmodel);

        }

        [HttpPost]
        public ActionResult Cadastrar(Unidade unidade)
        {
            if (ModelState.IsValid)
            {
                unidade.DataCadastro = DateTime.Now;
                _unit.UnidadeRepository.Cadastrar(unidade);
                _unit.Salvar();
                TempData["mensagem"] = "Unidade cadastrada com sucesso!";
                return RedirectToAction("ListarUnidades");
            }
            else
            {
                return View("Cadastrar");
            }

        }

        [HttpPost]
        public ActionResult Editar(Unidade unidade)
        {

            _unit.UnidadeRepository.Atualizar(unidade);
            _unit.Salvar();
            TempData["mensagem"] = "Unidade editada com sucesso!";
            return RedirectToAction("ListarUnidades");


        }

        [HttpPost]
        public ActionResult Excluir(int IDUnidade)
        {
            _unit.UnidadeRepository.Remover(IDUnidade);
            _unit.Salvar();
            TempData["mensagem"] = "Unidade removida com sucesso!";
            return RedirectToAction("ListarUnidades");
        }

        private SelectList ListarUnidade()
        {
            var lista = _unit.UnidadeRepository.Listar();
            return new SelectList(lista, "IDUnidade", "Nome");
        }

        protected override void Dispose(bool disposing)
        {
            _unit.Dispose();
            base.Dispose(disposing);
        }
    }
}

HelpOn/Views/Shared/ListaChamados.cshtml
@model HelpOn.Web.ViewModel.ChamadoViewModel
@{
    ViewBag.Title = "Lista de Chamados";
    
}

<h2>Lista de Chamados</h2>
@using (Ajax.BeginForm("Buscar", null, new AjaxOptions
{
    HttpMethod = "get",
    UpdateTargetId = "tabela",
    InsertionMode = InsertionMode.Replace
},
                new { @id = "formularioBusca", @class = "form-inline", @method = "get" }))
{
    <div class="col-md-3">
        <select name="Processo" class="form-control" id="ProcessoSelect">
            <option value="Aberto" selected="selected">Aberto</option>
            <option value="Em Processo">Em Processo</option>
            <option value="Fechado">Fechado</option>
            <option value="">Todos</option>
        </select>
    </div>
    <div class="col-md-3">
        <select name="NumeroAndar" class="form-control" id="LaboratorioSelect">
            @foreach (var andar in Model.Andares)
            {
                <option value="@andar.NumeroAndar">Unidade: @andar.Unidade.IDUnidade  Andar: @andar.NumeroAndar</option>
            }


        </select>
    </div>
}
<table class="table">
   <thead>
       <tr>
           <td>Chamado</td>
           <td>Status</td>
           <td>Unidade</td>
           <td>Andar</td>
           <td>Laboratorio</td>
           <td>Enviado para</td>
       </tr>
   </thead>
    <tbody id="tabela">
        @Html.Partial("_listaChamado", Model.Chamados)
    </tbody>
</table>
<!---- Modal ------>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirmação</h4>
            </div>
            <div class="modal-body">
                Deseja atender o chamado ?
            </div>
            <div class="modal-footer">
                @using (Ajax.BeginForm("AtenderChamado", null, new AjaxOptions
                {
                    HttpMethod = "post",
                    UpdateTargetId = "tabela",
                    InsertionMode = InsertionMode.Replace
                },
            new { @id = "mudaProcessos", @class = "form-inline", @method = "post" }))
                {
                    <input type="hidden" id="IDChamado" name="IDChamado" />
                    <button type="submit" class="btn btn-success botaoChamado" value="Aberto" id="Aberto" name="Processo">Aberto</button>
                    <button type="submit" class="btn btn-warning botaoChamado" value="Em Processo" id="EmProcesso" name="Processo">Em Processo</button>
                    <button type="submit" class="btn btn-danger botaoChamado" value="Fechado" id="Fechado" name="Processo">Fechado</button>
                    <button type="button" class="btn btn-default botaoFechaModel" data-dismiss="modal">Cancelar</button>
                }
            </div>
        </div>
    </div>
</div>

<input type="button" class="btn btn-primary" value="Atualizar" id="atualiza" />
@section scripts{
<script>
    $().ready(function () {

        
        var intervalo = window.setInterval(recarregaFormulario, 500);
        function recarregaFormulario() {
            $("#formularioBusca").submit();
        }

        $(".botaoChamado").click(function () {
                $(".botaoFechaModel").trigger('click');
                $(".botaoFechaModel").trigger('click');
        });

        $("#ProcessoSelect").change(function () {
            $("#formularioBusca").submit();
        });
        
        $("#LaboratorioSelect").change(function () {
            $("#formularioBusca").submit();
        });

    })

      

</script>
}

HelpOn/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HelpOn</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet">
    <script src="~/Scripts/modernizr-2.8.3.js"></script>

    <!--Icons-->
    <script src="~/Scripts/helpon.glyphs.js"></script>
  


</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><span>Help</span>On</a>
                <ul class="user-menu">
                    <li class="dropdown pull-right">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> User <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> Perfil</a></li>
                            <li><a href="#"><svg class="glyph stroked gear"><use xlink:href="#stroked-gear"></use></svg> Configurações</a></li>
                            <li>@Html.ActionLink("Sair", "Sair", "Login")</li>
                        </ul>
                    </li>
                </ul>
            </div>

        </div>
    </nav>

    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <form role="search">
            <div class="form-group">
               
            </div>
        </form>
        <ul class="nav menu">
            <li>@Html.ActionLink("Cadastrar funcionário", "Cadastrar", "Funcionario")</li>
            <li>@Html.ActionLink("Funcionários cadastrados", "ListarFuncionarios", "Funcionario")</li>
            <li>@Html.ActionLink("Cadastrar Unidades", "Cadastrar", "Unidade")</li>
            <li>@Html.ActionLink("Unidades cadastradas", "ListarUnidades", "Unidade")</li>
            <li>@Html.ActionLink("Andares", "Andares", "Unidade")</li>
            <li>@Html.ActionLink("Laboratórios", "Labs", "Unidade")</li>
           
        </ul>

    </div>

    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">

        @RenderBody()

    </div>	


    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.maskedinput.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    @RenderSection("scripts", false)
</body>

</html>

HelpOn/Views/Shared/_listaChamado.cshtml
@model List<HelpOn.Dominio.Models.Chamado>

       
    
    
        @foreach (var chamado in Model)
        {
            
            
            <tr>
                <td>@chamado.Descricao.Nome</td>
                <td>
                    @if (chamado.Processo == "Aberto")
                    {
                        <button onclick="IDChamado.value = @chamado.IDChamado" type="button" 
                                class="btn btn-success" data-toggle="modal" data-target="#myModal">
                            @chamado.Processo
                        </button>
                    }
                    else if (chamado.Processo == "Em Processo")
                    {
                        <button onclick="IDChamado.value = @chamado.IDChamado" type="button"
                                class="btn btn-warning " data-toggle="modal" data-target="#myModal">
                            @chamado.Processo
                        </button>
                    }
                    else
                    {
                        <button onclick="IDChamado.value = @chamado.IDChamado" type="button"
                                class="btn btn-danger" data-toggle="modal" data-target="#myModal">
                            @chamado.Processo
                        </button>
                    }
                    
                </td>
                <td>@chamado.IDUnidade</td>
                <td>@chamado.NumeroAndar</td>
                <td>@chamado.NumeroLab</td>
                <td>
                    @if (chamado.IDNivel == 2)
                    {
                        @:HelpDesk
                    }
                    else if(chamado.IDNivel == 3)
                    {
                        @:Monitor
                    }
                </td>
            </tr>
            
        
    }