HelpOn/Controllers/ChamadoController.cs
using HelpOn.Dominio.Models;
using HelpOn.Persistencia.UnitOfWork;
using HelpOn.Web.Filtros;
using HelpOn.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HelpOn.Web.Controllers
{
    [AutorizacaoFilter]
    public class ChamadoController : Controller
    {
        private Funcionario _usuarioLogado;
        private UnitOfWork _unit = new UnitOfWork();

        // GET: Chamado
        public ActionResult Index()
        {
            _usuarioLogado = (Funcionario)Session["usuarioLogado"];
            var viewModel = new ChamadoViewModel()
            {
                Andares = _unit.AndarRepository.Listar(),
                ListaAndar = ListaAndar(),
                Chamados = _unit.ChamadoRepository.BuscarChamadosAbertos(_usuarioLogado.IDNivel)
               

                
            };
            return View("ListaChamados",viewModel);
        }

        [HttpGet]
        public ActionResult Buscar(string Processo, int? NumeroAndar)
        {
            ICollection<Chamado> lista;
            _usuarioLogado = (Funcionario)Session["usuarioLogado"];
            if (_usuarioLogado.IDNivel != 1)
            {
                lista = _unit.ChamadoRepository.BuscarPor((c => c.Processo.Contains(Processo) &&
                (c.NumeroAndar == NumeroAndar || Processo == null) && c.IDNivel == _usuarioLogado.IDNivel));
            }
            else
            {
                lista = _unit.ChamadoRepository.BuscarPor((c => c.Processo.Contains(Processo) &&
          (c.NumeroAndar == NumeroAndar || Processo == null)));
            }
          


            return PartialView("_listaChamado", lista);
        }

        [HttpPost]
        public ActionResult AtenderChamado(int IDChamado, String Processo)
        {
            _usuarioLogado = (Funcionario)Session["usuarioLogado"];
            var chamado = _unit.ChamadoRepository.BuscarPorId(IDChamado);
            chamado.Processo = Processo;
            _unit.ChamadoRepository.Atualizar(chamado);
            _unit.Salvar();
            ICollection<Chamado> lista = _unit.ChamadoRepository.BuscarChamadosAbertos(_usuarioLogado.IDNivel);
            return PartialView("_listaChamado", lista);
        }

        public SelectList ListaAndar()
        {
            var lista = _unit.AndarRepository.Listar();
            return new SelectList(lista, "NumeroAndar", "IDUnidade");
        }

        //Cadastrar Chamado Monitor
        [HttpPost]
        public ActionResult Cadastrar(ChamadoViewModel chamadoViewModel)
        {
            var chamado = new Chamado()
            {
                DataChamado = chamadoViewModel.DataChamado,
                Processo = chamadoViewModel.Processo,
                NumeroLab = chamadoViewModel.NumeroLab,
                NumeroAndar = chamadoViewModel.NumeroAndar,
                IDUnidade = chamadoViewModel.IDUnidade,
                IDNivel = chamadoViewModel.IDNivel,
                IDDescricao = chamadoViewModel.IDDescricao
                

            };

            _unit.ChamadoRepository.Cadastrar(chamado);
            _unit.Salvar();


            return RedirectToAction("Solicitacao", "Laboratorio");
        }
    }
}

HelpOn/Controllers/LaboratorioController.cs
using HelpOn.Dominio.Models;
using HelpOn.Persistencia.UnitOfWork;
using HelpOn.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace HelpOn.Controllers
{
    public class LaboratorioController : Controller
    {
        private UnitOfWork _unit = new UnitOfWork();

        
        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult GetDescricao()
        {
            var lista = _unit.DescricaoRepository.Listar().Select(d => new { id = d.IDDescricao, descricao = d.Nome });
            return Json(lista,JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult Solicitacao()
        {
            Session["usuarioLogado"] = new Funcionario
            {
                Nome = "Professor"
            };
            int IPLab = GetIp();

            var viewModel = new ChamadoViewModel()
            {
                Lab = _unit.LaboratorioRepository.BuscarPorUnitario(lab => lab.NumeroLab == IPLab),
                Descricoes = _unit.DescricaoRepository.Listar(),
                Chamados = _unit.ChamadoRepository.BuscarPor(c => c.NumeroLab == IPLab)
                
                

            };
            return View(viewModel);
        }

        
        [HttpGet]
        public PartialViewResult ListarSolicitacoes()
        {

            int IPLab = GetIp();
            var viewModel = new ChamadoViewModel()
            {
                Lab = _unit.LaboratorioRepository.BuscarPorUnitario(lab => lab.NumeroLab == IPLab),
                Descricoes = _unit.DescricaoRepository.Listar(),
                Chamados = _unit.ChamadoRepository.BuscarPor(c => c.NumeroLab == IPLab)

            };
            return PartialView(viewModel.Chamados);
        }

        private static int GetIp()
        {
            //string IP = Request.UserHostAddress.ToString();

            string IP = "10.20.21.41";

            //Captura a substring do IP e constrói o número do Laboratório
            StringBuilder ips = new StringBuilder();
            ips.Append(IP.Substring(6, 1));
            ips.Append("0");
            ips.Append(IP.Substring(7, 1));
            IP = ips.ToString();
            var IPLab = Int32.Parse(IP);
            return IPLab;
        }

    }
}

HelpOn/Views/Laboratorio/Laboratorio.cshtml
@model HelpOn.Web.ViewModel.ChamadoViewModel
@{
    ViewBag.Title = "Laboratorio";
}

<h2>Laboratorio</h2>


<div id="botoes">
    @foreach (var descricao in Model.Descricoes)
    {
        if ((descricao.IDDescricao % 2) == 1)
        {
            <div style="float:left;width:49%">
                <button class="btn btn-custom btn-lg btn-block" float="left" data-toggle="modal" data-target="#myModal">@descricao.Nome</button>
            </div>
        }
        else
        {
            <div style="float:right;width:49%">
                <button class="btn btn-custom btn-lg btn-block" float="right" data-toggle="modal" data-target="#myModal">@descricao.Nome</button>
            </div>
        }

    }
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span><button>
                        <h4 class="modal-title" id="myModalLabel">Atenção!</h4>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Cadastrar", "Chamado", "POST"))
                {
                    @Html.HiddenFor(c => c.IDDescricao)
                    @Html.HiddenFor(c => c.Processo, new { @Value = "Aberto" })
                    @Html.HiddenFor(c => c.NumeroLab, new { @Value = Model.Lab.NumeroLab })
                    @Html.HiddenFor(c => c.NumeroAndar, new { @Value = Model.Lab.NumeroAndar })
                    @Html.HiddenFor(c => c.IDUnidade, new { @Value = Model.Lab.IDUnidade })
                    @Html.HiddenFor(c => c.DataChamado, new { @Value = DateTime.Now })
                    @Html.HiddenFor(c => c.IDNivel, new { @Value = 1 })

                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-custom">Enviar Solicitação</button>
                }
            </div>
        </div>
    </div>
</div>





@section scripts{
 <script>
     $().ready(function () {

                  $("#botoes button").click(function () {
                  if ($(this).html() == "Solicitar Monitor") {
                  $("#IDDescricao").val(1);
                  $(".modal-body").html("Deseja Realmente solicitar um Monitor?");
             } else
                  if ($(this).html() == "Bloquear Internet") {
                      $("#IDDescricao").val(2);
                      $(".modal-body").html("Deseja realmente solicitar o bloqueio da Internet no Laboratório?");
             } else
                      if ($(this).html() == "Liberar Internet") {
                          $("#IDDescricao").val(3);
                          $(".modal-body").html("Deseja realmente solicitar a liberação da Internet no Laboratório?");
             } else
                          if ($(this).html() == "Bloquear HD Público") {
                              $("#IDDescricao").val(4);
                              $(".modal-body").html("Deseja realmente solicitar o bloqueio do HD Público no Laboratório?");
             } else
                              if ($(this).html() == "Liberar HD Público") {
                                  $("#IDDescricao").val(5);
                                  $(".modal-body").html("Deseja realmente solicitar a liberação do HD Público no Laboratório?");
             } else
                                  if ($(this).html() == "Bloquear Portal do Aluno") {
                                      $("#IDDescricao").val(6);
                                      $(".modal-body").html("Deseja realmente solicitar o bloqueio do Portal do Aluno no Laboratório?");
             } else
                                      if ($(this).html() == "Liberar Portal do Aluno") {
                                          $("#IDDescricao").val(7);
                                          $(".modal-body").html("Deseja realmente solicitar a liberação do Portal do Aluno no Laboratório?");
             } else
                                          if ($(this).html() == "Alterar °C Ar Condicionado") {
                                              $("#IDDescricao").val(8);
                                              $(".modal-body").html("Deseja realmente solicitar a alteração de Temperatura do Ar Condicionado no Laboratório?");
             }
         });
      });
</script>
}

HelpOn/Views/Laboratorio/ListarSolicitacoes.cshtml
@model List<HelpOn.Dominio.Models.Chamado>

      <p>
          <br />
    </p> 
    
    
        @foreach (var chamado in Model)
        {
            
            
            <tr>
                <td>@chamado.Descricao.Nome</td>
                <td>
                    @if (chamado.Processo == "Aberto")
                    {
                    <h4>
                        <span id="status" class="label label-success">@chamado.Processo</span>
                    </h4>
                    }
                    else if (chamado.Processo == "Em Processo")
                    {
                        <h4>
                            <span id="status" class="label label-warning">@chamado.Processo</span>
                        </h4>
                    }
                    else
                    {
                        <h4>
                            <span id="status" class="label label-danger">@chamado.Processo</span>
                        </h4>
                    }
                </td>
                <td>@chamado.IDUnidade</td>
                <td>@chamado.NumeroAndar</td>
                <td>@chamado.NumeroLab</td>
                <td>
                    @if (chamado.IDNivel == 2)
                    {
                        @:HelpDesk
                    }
                    else if(chamado.IDNivel == 3)
                    {
                        @:Monitor
                    }
                </td>
            </tr>
            
    }

HelpOn/Views/Laboratorio/Solicitacao.cshtml
@model HelpOn.Web.ViewModel.ChamadoViewModel

@{
    ViewBag.Title = "Laboratório";
}

<h2>Solicitações de Laboratório</h2>


<section id="botoes" style="height:220px">
    @foreach (var descricao in Model.Descricoes)
    {
        if ((descricao.IDDescricao % 2) == 1)
        {
            <div style="float:left;width:49%;height:50px">
                <button class="btn btn-custom btn-lg btn-block" float="left" data-toggle="modal" data-target="#myModal">@descricao.Nome</button>
            </div>

        }
        else
        {
            <div style="float:right;width:49%;height:50px">
                <button class="btn btn-custom btn-lg btn-block" float="right" data-toggle="modal" data-target="#myModal">@descricao.Nome</button>
            </div>

        }

    }
</section>



<div class="table-responsive" >
    <div class="panel panel-default">
        <div class="panel-heading">
            Lista de Solicitações - Laboratório @Model.Lab.NumeroLab
        </div>

        <table class="table table-hover">
            <thead>
                <tr>
                    <td>Chamado</td>
                    <td>Status</td>
                    <td>Unidade</td>
                    <td>Andar</td>
                    <td>Laboratorio</td>
                    <td>Enviado para</td>
                </tr>
            </thead>
            <tbody id="tabela">
                @Html.Partial("ListarSolicitacoes", Model.Chamados)
            </tbody>
        </table>
    </div>

    
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Atenção!</h4>
            </div>
            <div class="modal-body">
                <p>Deseja Realmente Enviar esta Solicitação?</p>
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Cadastrar", "Chamado", "POST"))
                {
                    @Html.HiddenFor(c => c.IDDescricao)
                    @Html.HiddenFor(c => c.Processo, new { @Value = "Aberto" })
                    @Html.HiddenFor(c => c.NumeroLab, new { @Value = Model.Lab.NumeroLab })
                    @Html.HiddenFor(c => c.NumeroAndar, new { @Value = Model.Lab.NumeroAndar })
                    @Html.HiddenFor(c => c.IDUnidade, new { @Value = Model.Lab.IDUnidade })
                    @Html.HiddenFor(c => c.DataChamado, new { @Value = DateTime.Now })
                    @Html.HiddenFor(c => c.IDNivel)


                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-custom">Enviar Solicitação</button>
                }
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script>
        function atualizarTabela() {
            $.ajax(
            {
                type: 'GET',
                url: "/Laboratorio/ListarSolicitacoes",
                
                success: function (data) {
                    $("#tabela").html(data);
                }
            });
            
        }


        $().ready(function () {

            $("#sidebar-collapse").css("visibility", "hidden");
            
           setInterval(atualizarTabela, 5000);

            $.ajax({
                url: "http://localhost:64222/Laboratorio/GetDescricao",
                type: "GET",
                success: function (data) {
                    $.each(data, function (index, des) {
                        $("#botoes button").click(function () {
                            if ($(this).html() == des.descricao) {
                                $("#IDDescricao").val(des.id);                                
                                $(".modal-title").html("Atenção - " + des.descricao);
                                if (des.id == 1) {
                                    $("#IDNivel").val(3);
                                } else {
                                    $("#IDNivel").val(2);
                                }
                            }
                        });
                    });
                }
            });
        });
    </script>
}